algoritmo "semnome"
// Função :
// Autor :
// Data : 09/10/2022
// Seção de Declarações 
var
nome:caractere
horas: inteiro
valor, M: real
inicio
escreva("digite seu nome, ")
leia (nome)
escreva ("informe quantas horas você trabalhou: ")
leia (horas)
escreva ("qual o valor da hora trabalhada: ")
leia (valor)
M <- horas * valor
escreva ("ola, ", nome, " seu salario esse mes é de ", M)

fimalgoritmo
